### PR TITLE
Dev improvements

### PR DESCRIPTION
**Pull request by justinbalaguer**
image
image

solves all warnings for using `>` instead of `&gt;`
this PR also updates `README.md` and adds `.gitignore` to remove `node_modules` and `dist` when devs PR

### CODE REVIEW

**Comment by devadigapratham** [comment]
!bounty 10

**Comment by devadigapratham** [comment]
!bounty 0

**Comment by bun137** [comment]
@devadigapratham  why reset score to 0?

**Comment by devadigapratham** [comment]
@bun137 he wasnt from pes🤡

**Pull request merged**
